export const APP_INIT = "APP_INIT";

export const FETCH_LIST_SUCCESS = "FETCH_LIST_SUCCESS";
export const FETCH_LIST_ERROR = "FETCH_LIST_ERROR";

export const UPDATE_ITEM_SUCCESS = "UPDATE_ITEM_SUCCESS";
export const UPDATE_ITEM_ERROR = "UPDATE_ITEM_ERROR";

export const TOGGLE_LIST_ITEM = "TOGGLE_LIST_ITEM";

export const DELETE_LIST_ITEM = "DELETE_LIST_ITEM";
